"""Initial tables

Revision ID: 96e7e6cff5f3
Revises: 
Create Date: 2025-11-15 01:19:18.579254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96e7e6cff5f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcasts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('podcast_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('podcast_url', sa.String(), nullable=False),
    sa.Column('podcast_image', sa.String(), nullable=False),
    sa.Column('episode_image', sa.String(), nullable=True),
    sa.Column('enclosure_url', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date_published', sa.DateTime(), nullable=False),
    sa.Column('host_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_episode_host_questions', 'episodes', ['host_questions'], unique=False)
    op.create_index('ix_episode_question_answers', 'episodes', ['question_answers'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_episode_id'), 'transcripts', ['episode_id'], unique=True)
    op.create_table('podcast_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transcript_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('gist', sa.String(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_utterances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.String(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.String(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_words')
    op.drop_table('transcript_utterances')
    op.drop_table('transcript_chapters')
    op.drop_table('podcast_categories')
    op.drop_index(op.f('ix_transcripts_episode_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_episode_question_answers', table_name='episodes')
    op.drop_index('ix_episode_host_questions', table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('podcasts')
    # ### end Alembic commands ###
