"""removed index from host_questions and question_answers columns oin episode table

Revision ID: a5316d046dc3
Revises: 96e7e6cff5f3
Create Date: 2025-11-15 19:46:09.535017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5316d046dc3'
down_revision: Union[str, Sequence[str], None] = '96e7e6cff5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_host_questions'), table_name='episodes')
    op.drop_index(op.f('ix_episode_question_answers'), table_name='episodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_episode_question_answers'), 'episodes', ['question_answers'], unique=False)
    op.create_index(op.f('ix_episode_host_questions'), 'episodes', ['host_questions'], unique=False)
    # ### end Alembic commands ###
